#!/bin/zsh

HASH="%C(yellow)%h%C(reset)"
RELATIVE_TIME="%C(green)(%cr)%C(reset)"
AUTHOR="%C(bold blue)<%an>%C(reset)"
REFS="%C(red)%d%C(reset)"
SUBJECT="%C(reset)%s%C(reset)"

FORMAT="$HASH{$RELATIVE_TIME{$AUTHOR{$REFS $SUBJECT"

function gitPrettyLog() {
  git log --graph --pretty="tformat:$FORMAT" $* |
  sed -e 's/\(years\{0,1\}\).*ago)/\1)/' -e 's/ ago//' |
  column -t -s '{' |
  less -SXRF
}
