call pathogen#infect()
call pathogen#helptags()

" Mappings
let mapleader=","

for f in split(glob('~/.vim/rc/*.vim'), '\n')
  exe 'source' f
endfor

for f in split(glob('~/.vim/rc.local/*.vim'), '\n')
  exe 'source' f
endfor
