# the default umask is set in /etc/login.defs
umask 022

# set PATH so it includes user's private bin if it exists
[[ -d ~/bin ]] && export PATH=~/bin:"${PATH}"

[[ "$TERM" != "dumb" ]] && export GREP_OPTIONS='--color=auto'
