ZCONFDIR="$HOME/.dotfiles/zsh"
HISTFILE=~/.histfile
HISTSIZE=10000000
SAVEHIST=10000000
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY
setopt INTERACTIVE_COMMENTS
setopt NOMATCH
setopt NOTIFY
setopt VI # Not required, as EDITOR/VISUAL are set, but still handy

EDITOR=vim

MANPAGER="zsh -c \"col -b | /usr/bin/vim -R \
  -c 'set nonumber' \
  -c 'set nolist' \
  -c 'set nomodifiable' \
  -c 'set syntax=man' -\""
LESS=FRSX
PAGER=less

export HISTFILE HISTSIZE SAVEHIST EDITOR MANPAGER LESS PAGER

# the default umask is set in /etc/login.defs
umask 022

# set PATH so it includes user's private bin if it exists
[[ -d ~/bin ]] && export PATH=~/bin:"${PATH}"

[[ "$TERM" != "dumb" ]] && export GREP_OPTIONS='--color=auto'

[[ -d $ZCONFDIR/functions ]] && fpath=($ZCONFDIR/functions $fpath)
[[ -d $ZCONFDIR/functions.local ]] && fpath=($ZCONFDIR/functions.local $fpath)

[[ -d $ZCONFDIR/functions ]] && autoload $ZCONFDIR/functions/*(:t)
[[ -d $ZCONFDIR/functions.local ]] && autoload $ZCONFDIR/functions.local/*(:t)

source_if_readable $ZCONFDIR/zshenv.local
