# Autoloads
autoload -U compinit promptinit edit-command-line
compinit
promptinit

# Editing command lines in vim
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# Output time for stuff that runs longer that 5 seconds. In zshrc since it only
# makes sense for interactive shells.
REPORTTIME=5
export REPORTTIME

# If go is installed and has zsh completion info, source it.
[[ -r $(go env GOROOT)/misc/zsh/go ]] && . $(go env GOROOT)/misc/zsh/go ]]

# Common aliases
[[ -r $ZCONFDIR/zsh-aliases.common ]] && . $ZCONFDIR/zsh-aliases.common

# Look for and source platform specific files.
[[ -r $ZCONFDIR/zshrc.$(uname -s) ]] && . $ZCONFDIR/zshrc.$(uname -s)
[[ -r $ZCONFDIR/zsh-aliases.$(uname -s) ]] && . $ZCONFDIR/zsh-aliases.$(uname -s)

# Source machine local files if they exist.
[[ -r $ZCONFDIR/zshrc.local ]] && . $ZCONFDIR/zshrc.local
[[ -r $ZCONFDIR/zsh-aliases.local ]] && . $ZCONFDIR/zsh-aliases.local

# Prompt
[[ -r $ZCONFDIR/zsh-prompt ]] && . $ZCONFDIR/zsh-prompt
