HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY
setopt VI # Not required, as EDITOR/VISUAL are set, but still handy

EDITOR=vim

MANPAGER="zsh -c \"col -b | /usr/bin/vim -R -c 'set nonumber' -c 'set syntax=man' -\""

export HISTFILE HISTSIZE SAVEHIST EDITOR MANPAGER

# Autoloads
autoload -U compinit promptinit
compinit
promptinit

# Common aliases
[[ -r ~/.zsh/zsh-aliases.common ]] && . ~/.zsh/zsh-aliases.common

case $(uname) in
	(Linux)
		[[ -r ~/.zsh/zshrc.linux ]] && . ~/.zsh/zshrc.linux
		[[ -r ~/.zsh/zsh-aliases.linux ]] && . ~/.zsh/zsh-aliases.linux
	;;
	(Darwin)
		[[ -r ~/.zsh/zshrc.darwin ]] && . ~/.zsh/zshrc.darwin
		[[ -r ~/.zsh/zsh-aliases.darwin ]] && . ~/.zsh/zsh-aliases.darwin
	;;
esac

# Source local files if they exist.
[[ -r ~/.zsh/zshrc.local ]] && . ~/.zsh/zshrc.local
[[ -r ~/.zsh/zsh-aliases.local ]] && . ~/.zsh/zsh-aliases.local

# Prompt
prompt clint
